package org.example;

// TODO: V SIMULACNOM JADRE PRI PLANOVANI UDALOSTI PRIDAT CHECK,
// TODO: ZE UDALOST, KTORA JE PRAVE PLANOVANA NEMA CAS MENSI
// TODO: AKO VSETKY OSTATNE UDALOSTI V KALENDARI

// TODO: OSETRIT SITUACIU, KED DVE ALEBO VIAC UDALOSTI SU NAPLANOVANE
// TODO: NA ROVNAKY CAS, BUDE POTREBNE PRIDAT PRIROTIY UDALOSTIAMS

import org.example.GUI.HlavneOkno;

public class Main
{
    public static void main(String[] args)
    {
        new HlavneOkno();
    }
}
