/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.NewGUI.Okno;

import org.example.NewGUI.ISimulationDelegate;
import org.example.Ostatne.Konstanty;
import org.example.Ostatne.Prezenter;
import org.example.Simulacia.Jadro.SimulacneJadro;
import org.example.Simulacia.System.SimulaciaSystem;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Niko
 */
public class HlavneOkno extends javax.swing.JFrame implements ISimulationDelegate
{

    private SimulaciaSystem simulacia;
    private Thread simulacneVlakno;

    /**
     * Creates new form HlavneOkno
     */
    public HlavneOkno() {
        initComponents();
        this.inicializacia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputPocetReplikacii = new javax.swing.JTextField();
        inputNasada = new javax.swing.JTextField();
        inputPocetObsluznychMiest = new javax.swing.JTextField();
        inputPocetPokladni = new javax.swing.JTextField();
        buttonStart = new javax.swing.JButton();
        buttonPauza = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        sliderRychlost = new javax.swing.JSlider();
        labelRychlost = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelSimulacnyCas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelAktualnaReplikacia = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelCelkovyCasSystem = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabulkaAgenti = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabulkaPokladne = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabulkaOkna = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pocet replikacii:");

        jLabel2.setText("Nasada (prazdne pre nahodnu nasadu):");

        jLabel3.setText("Pocet obsluznych miest:");

        jLabel4.setText("Pocet pokladni:");

        buttonStart.setText("Start");
        buttonStart.setMaximumSize(new java.awt.Dimension(72, 50));
        buttonStart.setMinimumSize(new java.awt.Dimension(72, 50));
        buttonStart.setPreferredSize(new java.awt.Dimension(72, 50));
        buttonStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonStartMouseClicked(evt);
            }
        });

        buttonPauza.setText("Pauza");
        buttonPauza.setMaximumSize(new java.awt.Dimension(72, 50));
        buttonPauza.setMinimumSize(new java.awt.Dimension(72, 50));
        buttonPauza.setPreferredSize(new java.awt.Dimension(72, 50));
        buttonPauza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPauzaMouseClicked(evt);
            }
        });

        buttonStop.setText("Stop");
        buttonStop.setMaximumSize(new java.awt.Dimension(72, 50));
        buttonStop.setMinimumSize(new java.awt.Dimension(72, 50));
        buttonStop.setPreferredSize(new java.awt.Dimension(72, 50));
        buttonStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonStopMouseClicked(evt);
            }
        });

        sliderRychlost.setMajorTickSpacing(100);
        sliderRychlost.setMaximum(1000);
        sliderRychlost.setMinorTickSpacing(10);
        sliderRychlost.setPaintLabels(true);
        sliderRychlost.setPaintTicks(true);
        sliderRychlost.setSnapToTicks(true);
        sliderRychlost.setToolTipText("Rychlost");
        sliderRychlost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sliderRychlostMouseReleased(evt);
            }
        });

        labelRychlost.setText("n/a");

        jLabel6.setText("Simulacny cas:");

        labelSimulacnyCas.setText("n/a");
        labelSimulacnyCas.setMaximumSize(new java.awt.Dimension(100, 16));
        labelSimulacnyCas.setMinimumSize(new java.awt.Dimension(100, 16));
        labelSimulacnyCas.setPreferredSize(new java.awt.Dimension(100, 16));

        jLabel8.setText("Aktualna replikacia:");

        labelAktualnaReplikacia.setText("n/a");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Celkove statistiky:");

        jLabel7.setText("Priemerny cas v systeme:");

        labelCelkovyCasSystem.setText("n/a");

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Statistiky aktualnej replikacie:");

        jLabel10.setText("Nieco:");

        jLabel11.setText("n/a");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Tabulka agenti:");

        tabulkaAgenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Typ", "S. system", "S. automat", "K. automat", "S. obsluha", "K. obsluha", "S. pokladna", "K. pokladna", "S. vyzdvihnutie", "K. vyzdvihnutie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabulkaAgenti);

        tabulkaPokladne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Obsadenost", "Vytazenie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabulkaPokladne);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Tabulka obsluzni zamestnanci:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Tabulka pokladne:");

        tabulkaOkna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Typ", "Obsadenost", "Vytazenie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabulkaOkna);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputPocetPokladni, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputPocetObsluznychMiest, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputPocetReplikacii, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNasada, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonPauza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(626, 626, 626)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(buttonStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(labelSimulacnyCas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(labelAktualnaReplikacia))
                                .addGap(37, 37, 37)
                                .addComponent(sliderRychlost, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(labelRychlost)))
                        .addGap(49, 49, 49))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filler3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(labelCelkovyCasSystem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(inputPocetReplikacii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputNasada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputPocetObsluznychMiest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(inputPocetPokladni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sliderRychlost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSimulacnyCas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAktualnaReplikacia)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRychlost, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonStop, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(buttonPauza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCelkovyCasSystem)
                .addGap(43, 43, 43)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );

        inputPocetReplikacii.getAccessibleContext().setAccessibleName("inputPocetReplikacii");
        inputNasada.getAccessibleContext().setAccessibleName("inputNasada");
        inputPocetObsluznychMiest.getAccessibleContext().setAccessibleName("inputPocetObsluznychMiest");
        inputPocetPokladni.getAccessibleContext().setAccessibleName("inputPocetPokladni");
        buttonStart.getAccessibleContext().setAccessibleName("buttonStart");
        buttonPauza.getAccessibleContext().setAccessibleName("buttonPauza");
        buttonStop.getAccessibleContext().setAccessibleName("buttonStop");
        sliderRychlost.getAccessibleContext().setAccessibleName("sliderRychlost");
        labelRychlost.getAccessibleContext().setAccessibleName("labelRychlost");
        labelSimulacnyCas.getAccessibleContext().setAccessibleName("labelSimulacnyCas");
        labelAktualnaReplikacia.getAccessibleContext().setAccessibleName("labelAktualnaReplikacia");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStartMouseClicked
        try
        {
            this.inicializujSimulaciu();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(HlavneOkno.this, "Neplatne zadane parametre simulacie!");
        }
    }//GEN-LAST:event_buttonStartMouseClicked

    private void sliderRychlostMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderRychlostMouseReleased
        int rychlost = HlavneOkno.this.getRychlost();
        if (rychlost >= Konstanty.MAX_RYCHLOST)
        {
            HlavneOkno.this.labelRychlost.setText("MAX");
        }
        else
        {
            HlavneOkno.this.labelRychlost.setText(rychlost + "x");
        }

        if (HlavneOkno.this.simulacia != null)
        {
            HlavneOkno.this.simulacia.setRychlost(rychlost);
        }
    }//GEN-LAST:event_sliderRychlostMouseReleased

    private void buttonPauzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPauzaMouseClicked
        this.toggleSimulaciaPozastavena();
    }//GEN-LAST:event_buttonPauzaMouseClicked

    private void buttonStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonStopMouseClicked
        this.ukonciSimulaciu();
    }//GEN-LAST:event_buttonStopMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HlavneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HlavneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HlavneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HlavneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HlavneOkno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPauza;
    private javax.swing.JButton buttonStart;
    private javax.swing.JButton buttonStop;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JTextField inputNasada;
    private javax.swing.JTextField inputPocetObsluznychMiest;
    private javax.swing.JTextField inputPocetPokladni;
    private javax.swing.JTextField inputPocetReplikacii;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelAktualnaReplikacia;
    private javax.swing.JLabel labelCelkovyCasSystem;
    private javax.swing.JLabel labelRychlost;
    private javax.swing.JLabel labelSimulacnyCas;
    private javax.swing.JSlider sliderRychlost;
    private javax.swing.JTable tabulkaAgenti;
    private javax.swing.JTable tabulkaOkna;
    private javax.swing.JTable tabulkaPokladne;
    // End of variables declaration//GEN-END:variables

    private void inicializacia()
    {
        this.inicializujSlider();
    }

    private void inicializujSimulaciu()
    {
        if (this.simulacia != null)
        {
            this.ukonciSimulaciu();
            this.resetujGUI();
        }

        int pocetReplikacii = Integer.parseInt(this.inputPocetReplikacii.getText());
        boolean nasadaZadana = !this.inputNasada.getText().isEmpty();
        int nasada = (nasadaZadana ? Integer.parseInt(this.inputNasada.getText()) : -1);

        int pocetObsluznychMiest = Integer.parseInt(this.inputPocetObsluznychMiest.getText());
        int pocetPokladni = Integer.parseInt(this.inputPocetPokladni.getText());

        if (pocetObsluznychMiest < 3)
        {
            throw new RuntimeException("Pocet okien nemoze byt mensi ako 3!");
        }

        this.simulacia = new SimulaciaSystem(pocetReplikacii, this.getRychlost(), Konstanty.OTVARACIA_DOBA_SEKUND,
            pocetObsluznychMiest, pocetPokladni, nasada, nasadaZadana);
        this.simulacia.pridajDelegata(this);

        this.simulacneVlakno = new Thread(() -> this.simulacia.simuluj());
        this.simulacneVlakno.setName("Simulacia");
        this.simulacneVlakno.setDaemon(true);
        this.simulacneVlakno.setPriority(Thread.MAX_PRIORITY);
        this.simulacneVlakno.start();
    }

    private void ukonciSimulaciu()
    {
        if (this.simulacia != null)
        {
            this.simulacia.ukonciSimulaciu();
            this.simulacia = null;
        }
    }

    private void toggleSimulaciaPozastavena()
    {
        if (this.simulacia != null)
        {
            this.simulacia.toggleSimulaciaPozastavena();
        }
    }

    private void resetujGUI()
    {
        this.labelAktualnaReplikacia.setText("n/a");
        this.labelSimulacnyCas.setText("n/a");

        this.labelCelkovyCasSystem.setText("n/a");

        ((DefaultTableModel)this.tabulkaAgenti.getModel()).setRowCount(0);
        ((DefaultTableModel)this.tabulkaOkna.getModel()).setRowCount(0);
        ((DefaultTableModel)this.tabulkaPokladne.getModel()).setRowCount(0);
    }

    private int getRychlost()
    {
        int zadanaRychlost = this.sliderRychlost.getValue();
        if (zadanaRychlost == 0)
        {
            return 1;
        }

        return zadanaRychlost;
    }

    private void inicializujSlider()
    {
        this.sliderRychlost.setValueIsAdjusting(true);
        this.sliderRychlost.setValue(Konstanty.DEFAULT_RYCHLOST);
        this.sliderRychlost.setValueIsAdjusting(false);

        this.labelRychlost.setText(Konstanty.DEFAULT_RYCHLOST + "x");
    }

    @Override
    public void aktualizujSa(SimulacneJadro simulacneJadro)
    {
        SimulaciaSystem simulacia = (SimulaciaSystem)simulacneJadro;

        // Celkove informacie
        Prezenter.aktualnaReplikacia(simulacia, this.labelAktualnaReplikacia);
        Prezenter.celkovyPriemernyCasSystem(simulacia, this.labelCelkovyCasSystem);

        // Informacie aktualnej replikacie
        Prezenter.simulacnyCas(simulacia, this.labelSimulacnyCas);
        Prezenter.tabulkaAgenti(simulacia, this.tabulkaAgenti);
        Prezenter.tabulkaOkna(simulacia, this.tabulkaOkna);
        Prezenter.tabulkaPokladne(simulacia, this.tabulkaPokladne);
    }
}
